## Project: Cholesky Decomposition Algorithms

<br> Trying to create a solver for Cholesky Decomposition 

In [44]:
import numpy as np
A = [[4,12,-16],[12,37,-43],[-16,-43,98]]

In [51]:
D = np.identity(3)
L = np.identity(3)
for i in range(0,3):
    for j in range(0,3):
        if i == j:
            D[i][j] = A[i][j] - sum((((L[j][k])**2)*D[k][k]) for k in range(0, j))
        elif i > j:
            L[i][j] = (A[i][j] - sum((L[i][k]*L[j][k]*D[k][k]) for k in range(0, j)))/D[j][j]
L_T = np.array(L)
print("The Cholesky Decomposition: \n")
print("Diagonal Matrix: \n")
print(D)
print("\n Lower Triangular Matrix: \n")
print(L)
print("\n Upper Triangular Matrix: \n")
print(L_T.T)

The Cholesky Decomposition: 

Diagonal Matrix: 

[[4. 0. 0.]
 [0. 1. 0.]
 [0. 0. 9.]]

 Lower Triangular Matrix: 

[[ 1.  0.  0.]
 [ 3.  1.  0.]
 [-4.  5.  1.]]

 Upper Triangular Matrix: 

[[ 1.  3. -4.]
 [ 0.  1.  5.]
 [ 0.  0.  1.]]


<br> Check if the Cholesky Decomposition are correct

In [60]:
LD = np.matmul(L,D)
A_clsky = np.matmul(LD, L_T.T)
A - A_clsky

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<br> Thus we show that the algorithms for Cholesky Decomposition works. ( Reminder: The Matrix must be symmetrical and positive definite! )