In [12]:
import numpy as np

#Simple Linear Algebra Equation of Ax = b 

A = np.matrix('3 1 1; 1 1 6; 1 4 7')
x = np.array([[1],[2],[3]])
A_inverse = A**(-1) 
b = A_inverse*x
print(b)
print(" ")

[[0.16326531]
 [0.24489796]
 [0.26530612]]
 


# Berechnung der Einheits-Matrize 

In [13]:
print(A*A**(-1))
print(" ")
print(A**(-1)*A)
print("\n Vergleich mit dem von NumPy: \n")
print(np.linalg.inv(A)*A)

[[ 1.00000000e+00  0.00000000e+00 -2.08166817e-17]
 [-1.38777878e-17  1.00000000e+00 -1.38777878e-17]
 [ 4.85722573e-17 -2.22044605e-16  1.00000000e+00]]
 
[[ 1.00000000e+00 -5.55111512e-17  1.38777878e-17]
 [ 0.00000000e+00  1.00000000e+00 -3.33066907e-16]
 [ 6.93889390e-18 -2.77555756e-17  1.00000000e+00]]

 Vergleich mit dem von NumPy: 

[[ 1.00000000e+00 -5.55111512e-17  1.38777878e-17]
 [ 0.00000000e+00  1.00000000e+00 -3.33066907e-16]
 [ 6.93889390e-18 -2.77555756e-17  1.00000000e+00]]


# Linear Algebra Tool NumPy 

<br/> solving simple Linear Algebra Equation through NumPy linalg Library 

In [14]:
from numpy import linalg
array = np.random.randint(1,10,size=(3,3))
A = np.matrix(array)
print(A)
print("\n Matrix Rank: \n")
print(linalg.matrix_rank(A))
print("\n Solving Matrix Determinant:\n")
print(linalg.det(A))
print("Solving Matrix Inverse: \n")
print(linalg.inv(A))
print("Matrix Rank: \n")
print(linalg.matrix_rank(A))
print("Eigenvalues and Eingenvectors: \n")
print(linalg.eig(A))

[[9 8 4]
 [4 3 3]
 [5 7 9]]

 Matrix Rank: 

3

 Solving Matrix Determinant:

-62.00000000000001
Solving Matrix Inverse: 

[[-0.09677419  0.70967742 -0.19354839]
 [ 0.33870968 -0.98387097  0.17741935]
 [-0.20967742  0.37096774  0.08064516]]
Matrix Rank: 

3
Eigenvalues and Eingenvectors: 

(array([17.1814259 ,  4.60259822, -0.78402412]), matrix([[-0.65432957, -0.61346135,  0.52776574],
        [-0.32863535, -0.05664095, -0.79499583],
        [-0.68106653,  0.78769091,  0.29907348]]))


### Trying out Cholesky Decomposition 


In [15]:
A = np.matrix('4 -3 0; -3 3 1; 0 1 2')
L = np.linalg.cholesky(A)
print(L)
# Check if the Decomposition is right
print(L*L.getT())

[[ 2.          0.          0.        ]
 [-1.5         0.8660254   0.        ]
 [ 0.          1.15470054  0.81649658]]
[[ 4. -3.  0.]
 [-3.  3.  1.]
 [ 0.  1.  2.]]


### Solving Linear Equation using Cholesky Decomposition 
<br> **Applying A = (L*L^(T))**
<p> Algorithms of Solving Linear Equations using Cholesky Decomposition: 
<p> Step 1: L*y = b
<p> Step 2: L^T*x = y
<p> Solve for x 

In [16]:
b = np.matrix('6;-2;8')
y = np.linalg.solve(L,b)
print(y)
print(" ")
x = np.linalg.solve(L.getT(),y)
print(x)

[[3.        ]
 [2.88675135]
 [5.71547607]]
 
[[-3.]
 [-6.]
 [ 7.]]
